version: '3.8'
services:
  s1:
    cpu_quota: 1500
    depends_on:
      - s2
      - s3
      - s4
      - s5
      - s6
    environment:
      - TYPE=master
      - INPUT=/data/bigtext.txt
    volumes:
      - ./target/debug:/src
      - ./data:/data
    image: 'mapreduce:v1'
    networks:
      - test
  s2:
    cpu_quota: 1500
    environment:
      - TYPE=slave
    image: 'mapreduce:v1'
    volumes:
      - ./target/debug:/src
      - ./data:/data
    networks:
      - test
  s3:
    cpu_quota: 1500
    environment:
      - TYPE=slave
    image: 'mapreduce:v1'
    volumes:
      - ./target/debug:/src
      - ./data:/data
    networks:
      - test
  s4:
    cpu_quota: 1500
    environment:
      - TYPE=slave
    image: 'mapreduce:v1'
    volumes:
      - ./target/debug:/src
      - ./data:/data
    networks:
      - test
  s5:
    cpu_quota: 1500
    environment:
      - TYPE=slave
    image: 'mapreduce:v1'
    volumes:
      - ./target/debug:/src
      - ./data:/data
    networks:
      - test
  s6:
    cpu_quota: 1500
    environment:
      - TYPE=slave
    image: 'mapreduce:v1'
    volumes:
      - ./target/debug:/src
      - ./data:/data
    networks:
      - test

networks:
  test:
