version: '3.8'
services:
  s1:
    cpu_quota: 3000
    depends_on:
      - s2
      - s3
      - s4
      - s5
      - s6
      - s7
      - s8
    environment:
      - TYPE=master
      - INPUT=/data/books.txt
    volumes:
      - ./target/debug:/src
      - ./data:/data
    image: 'mapreduce:v1'
    networks:
      - test
  s2:
    cpu_quota: 3000
    environment:
      - TYPE=worker
    image: 'mapreduce:v1'
    volumes:
      - ./target/debug:/src
      - ./data:/data
    networks:
      - test
  s3:
    cpu_quota: 3000
    environment:
      - TYPE=worker
    image: 'mapreduce:v1'
    volumes:
      - ./target/debug:/src
      - ./data:/data
    networks:
      - test
  s4:
    cpu_quota: 3000
    environment:
      - TYPE=worker
    image: 'mapreduce:v1'
    volumes:
      - ./target/debug:/src
      - ./data:/data
    networks:
      - test
  s5:
    cpu_quota: 3000
    environment:
      - TYPE=worker
    image: 'mapreduce:v1'
    volumes:
      - ./target/debug:/src
      - ./data:/data
    networks:
      - test
  s6:
    cpu_quota: 3000
    environment:
      - TYPE=worker
    image: 'mapreduce:v1'
    volumes:
      - ./target/debug:/src
      - ./data:/data
    networks:
      - test
  s7:
    cpu_quota: 3000
    environment:
      - TYPE=worker
    image: 'mapreduce:v1'
    volumes:
      - ./target/debug:/src
      - ./data:/data
    networks:
      - test
  s8:
    cpu_quota: 3000
    environment:
      - TYPE=worker
    image: 'mapreduce:v1'
    volumes:
      - ./target/debug:/src
      - ./data:/data
    networks:
      - test

networks:
  test:
