version: '3.8'
services:
  s1:
    image: 'ubuntu:22.04'
    cpu_quota: 3000
    environment:
      - TYPE=master
      - INPUT=/data/single_simple.txt
    volumes:
      - ./target/debug:/src
      - ../data:/data
    command: '/src/singlenode'
