version: '3.8'
services:
  s1:
    image: 'ubuntu'
    cpu_quota: 1500
    environment:
      - TYPE=master
      - INPUT=/data/bigtext.txt
    volumes:
      - ./target/debug:/src
      - ../data:/data
    command: '/src/singlenode'
